name: Build e Compactar Site Estático

on:
  push:
    branches:
      - main

jobs:
  build-and-zip:
    runs-on: ubuntu-latest

    steps:
      # 1. Baixa o seu código-fonte
      - name: Baixar o código
        uses: actions/checkout@v4

      # 2. Configura o Node.js
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      # 3. Instala as dependências
      - name: Instalar Dependências
        run: npm ci

      # 4. Gera os arquivos estáticos (cria a pasta 'out')
      - name: Gerar arquivos estáticos
        run: npm run build

      # 5. (Passo de zip REMOVIDO)

      # 6. Faz o Upload da pasta 'out' (ela será compactada automaticamente)
      - name: Fazer Upload do Artefato
        uses: actions/upload-artifact@v4
        with:
          name: site-pronto-para-hostinger
          path: out # <-- MUDANÇA IMPORTANTE: Agora aponta para a pasta 'out'